#!/usr/bin/env python
import sys
import requests

for arg in sys.argv:
    if arg == '-h' or arg == '--help':
        print('-s, --search - search for radios')
    elif arg == '-s' or arg == '--search':
        QUERY = input()
        BASE_URL = "https://de1.api.radio-browser.info/json/stations/byname/"
        OUTPUT_URL = BASE_URL + QUERY

        r = requests.get(OUTPUT_URL)
        response = r.json()
        for radio in response:
            url = radio['url_resolved']
            name = radio['name']
            print(f'Nazwa: {name}\nURL: {url}')
